# Generated by Django 5.1.7 on 2025-03-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_article_slug'),
        ('blog_app', '0009_comment'),
    ]

    operations = [
    ]
