# Generated by Django 5.1.7 on 2025-03-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_articlecountview_dislike_like'),
        ('blog_app', '0010_merge_0009_alter_article_slug_0009_comment'),
    ]

    operations = [
    ]
