# Generated by Django 5.1.7 on 2025-04-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_articleimage_article'),
        ('blog_app', '0014_alter_articleimage_article'),
    ]

    operations = [
    ]
